#!/usr/bin/env python
import sys
import smtplib
import getopt
import subprocess


# mail variables, more than one user can be specified using spaces as delimeters
# eg: toaddrs = 'bob@example.com alice@example.com mallory@example.com'
toaddrs = 'haroldr@gmail.com ovi.comes@gmail.com'
#toaddrs = 'haroldr@gmail.com'
fromaddr = 'worker_monitor@baderlab.org'

# dictionary of configuration files for each profile
configs = {
	'qa': '/etc/qa.broker.cfg', 
	'dev': '/etc/dev.broker.cfg', 
	'prod': '/etc/prod.broker.cfg'
}



def sendmail(subject, body):
	server = smtplib.SMTP('server1.baderlab.med.utoronto.ca')
	server.set_debuglevel(1)

	header = ('Subject: %s\r\nFrom: %s\r\nTo: %s\r\n\r\n' % (subject, fromaddr, ', '.join(toaddrs.split())))
	email = ''.join([header, body])
	server.sendmail(fromaddr, toaddrs.split(), email)
	server.quit()


def usage():
	print 'usage: %s [prod|qa|dev]' % sys.argv[0]


def main():
	if len(sys.argv) < 2:
		usage()
		sys.exit(0)

	if sys.argv[1] == 'prod':
		cfgfile = configs['prod']

	elif sys.argv[1] == 'qa':
		cfgfile = configs['qa']

	elif sys.argv[1] == 'dev':
		cfgfile = configs['dev']
	else:
		usage()
		sys.exit(0)

	# brokermgr returns 1 if no workers are running, in this case send an email to the user and 
	# restart the workers
	retcode = subprocess.call(['/usr/local/bin/brokermgr', 'stat', cfgfile])
	if retcode == 1:
		subject = ''.join(['Workers have stopped running on ', sys.argv[1]])
		#body = ''.join([sys.argv[1], ' workers have stopped running. Attempting to restart them automatically'])
		body = ''.join([sys.argv[1], ' workers have stopped running.'])
		sendmail(subject, body)

		#retcode = subprocess.call(['sudo', '-u', 'appserver', '/usr/local/bin/brokermgr', 'stop', cfgfile])
		#retcode = subprocess.call(['sudo', '-u', 'appserver', '/usr/local/bin/brokermgr', 'start', cfgfile])
		

if __name__ == '__main__':
	main()
