<h1>Media</h1>

<h2>11 Aug 2010</h2>
<h3>The University of Toronto Announces Free OpenHelix Tutorial and Training Materials for GeneMANIA, a Gene Function Prediction Tool</h3>
<p>The creators of GeneMANIA have contracted with OpenHelix to provide comprehensive online training for the gene function prediction tool (<a href="http://genemania.org">http://genemania.org</a>).</p>
<p>GeneMANIA is a free public resource that offers a simple, intuitive web interface that shows the relationships between genes in a list and analyzes and extends the list to include other related genes. The web interface is backed by powerful analysis software and a large data warehouse containing extensive amounts of existing functional genomics data, and also includes Cytoscape Web, a web based advanced visualization tool to enable browsing of query results and creation of publication-ready figures.</p>
<p>ÒGeneMANIA will soon be updated to include significantly increased functionality, according to Gary Bader and Quaid Morris, assistant professors in the Donnelly Centre (<a href="http://www.thedonnellycentre.utoronto.ca/">http://www.thedonnellycentre.utoronto.ca/</a>) and co-principal investigators for GeneMANIA. ÒOpenHelix based their tutorial on our development site, and even provided user feedback on our new features that resulted in improvements to our system. OpenHelix had very strong understanding of the GeneMANIA interface, which then translated into a powerful learning resource. The OpenHelix tutorial suite is sure to help current and new users to get up to speed on our site and its new features, and therefore get their results more quickly to support their research.</p>
<p>The new training initiatives include a free online tutorial suite on GeneMANIA. The online narrated tutorial (<a href="http://www.openhelix.com/genemania">http://www.openhelix.com/genemania</a>), which runs in just about any browser, can be viewed from beginning to end or navigated using chapters and forward and backward sliders. The approximately 60 minute tutorial highlights and explains the features and functionality needed to start using GeneMANIA effectively. The tutorial can be used by new users to introduce them to GeneMANIA, for previous users to view new features and functionality, or simply as a reference tool to understand specific features.</p>
<p>In addition to the tutorial, GeneMANIA users can also access useful training materials including the animated PowerPoint slides used as a basis for the tutorial, a suggested script for the slides, slide handouts, and exercises. This can save a tremendous amount time and effort for teachers and professors to create classroom content.</p>
<p>ÒGeneMANIA is an innovative, hypothesis generating tool that can be used to extend a given gene list to find related genes sharing similar functions, said OpenHelix founder and President Dr. Mary Mangan. ÒOpenHelix is excited to contribute to furthering the field of gene function prediction by assisting researchers in effectively and efficiently using such a critical tool.</p>
<p>Users can view the tutorials and download the free materials at <a href="http://www.openhelix.com">www.openhelix.com</a>.</p>
<p>In addition to the GeneMANIA tutorial suite, OpenHelix offers over 90 tutorial suites on some of the most powerful and popular bioinformatics and genomics tools available on the web. Some of the tutorials suites are freely available through support from the resource providers. The whole catalog of tutorials suites is available through a subscription. Users can view the tutorials and download the free materials at <a href="http://www.openhelix.com">www.openhelix.com</a>.</p>


<h2>22 Oct 2008</h2>
<h3>Donnelly Centre Researchers are Developing the "Google" of Biology.</h3>
<p>The goldmine of biological information uncovered by the Human Genome Project will now be quicker and easier to access thanks to a new "Google of Biology" developed by two University of Toronto researchers.</p>
<p>The program, known as GeneMANIA, is being developed by Drs. Gary Bader and Quaid Morris at the Terrence Donnelly Centre For Cellular and Biomolecular Research, and it aims to put the vast repository of biological data at the fingertips of all researchers.</p>
<p>In the current era of genome sequencing, high throughput technologies allow researchers to generate large amounts of data about genes, the genome and the cell. These immense data sets promise to tell us more about how biological systems work than ever before. However, powerful computers and software are needed to analyze them. Drs. Bader and Morris are developing the powerful new GeneMANIA software, funded by Genome Canada through the Ontario Genomics Institute, to help biologists gather meaningful information about genes from the large amounts of genomic data that are being produced. GeneMANIA will significantly help biologists make discoveries by using all available genomics information.</p>
<p>"Google brought the power of web search to the average Internet user by providing a simple, intuitive interface backed by powerful software and a massive collection of data. GeneMANIA will extend existing software prototypes to build a 'Google of Biology'" said Dr. Morris.</p>
<p>"It's a software system that lets biologists use all existing genomics and proteomics data to answer specific biological questions about gene function as quickly and easily as they perform a Google search."</p>
<p>GeneMANIA will combine extensive biological pathway information, a powerful algorithm, and user-friendly visualization tools. The GeneMANIA algorithms are based on the 'guilt-by-association' principle, where the query gene will be predicted to have the same function as genes that respond similarly in the large datasets. With the speed and accuracy of GeneMANIA, researchers will be better able to retrieve information from large datasets, allowing for more efficient and high impact research - like finding genes associated with different types of cancer, or identifying genes associated with drought resistance in plants.</p>
<p>GeneMANIA will integrate existing technologies (Pathway Commons and Cytoscape) and develop new ones to aid biologists in data analysis. Pathway Commons, built and maintained by the Memorial Sloan-Kettering Cancer Center and the University of Toronto, aims to be a central, convenient point of access for all publicly available pathway information, based on the cPath database software for storing, indexing and querying biological pathway and network information and the standard BioPAX pathway exchange format. Cytoscape, maintained by a large community of software developers across the world, including the University of Toronto, is software for network analysis and visualization. When a biologist inputs a gene or list of genes, GeneMANIA retrieves relevant pathway and network information from cPath, analyzes it and visualizes the results using Cytoscape.</p>
<p>To develop GeneMANIA, Drs. Bader and Morris have received funding from Genome Canada through the Ontario Genomics Institute. Additional funding was obtained from the National Institute of Health, the Canada Foundation for Innovation (CFI), the CFI-Infrastructure Operating Fund, the University of Toronto, Apple Canada, the Ontario Research Fund, and the Natural Science and Engineering Research Council of Canada.</p>
<p>Drs. Bader and Morris are both located in the Donnelly Centre for Cellular and Biomolecular Research at the University of Toronto, Canada's leading research and teaching institution.</p>
